### ISSUE TITLE
How does this script "talk" to jellyfin?

### ISSUE THREAD

**Issue by talesam** [pulpul-s/watchertoucher#2]
I configured your script, it's running, but I couldn't understand how it communicates with jellyfin to notify you that something has arrived. I tested it yesterday and it seemed to work, but today, I sent a movie and its script recognized it, but jellyfin didn't update it. My files are on a Drive Team mounted and configured with rclone.

Could you explain more about this script? Maybe I did something wrong.

**Comment by pulpul-s** [comment]
It doesn't. It only writes a dummy file on the filesystem and removes it immediately. The linux inotify system does not recognize filesystem changes that are made remotely on network filesystems (like cifs and nfs) and this is only a "poor workaround" to fix it. 

You can test that you have it configured correctly just by touching files yourself on the filesystem (e.g. running: touch test.mp4 or creating a file on windows) and see what the script outputs. Also look at your jellyfin logs from the dashboard to see the emby outputs.

read more about inotify: https://en.wikipedia.org/wiki/Inotify
